### ISSUE TITLE
[LR] CI/CD plugin failed

### ISSUE THREAD

**Issue by ittaLaRedoute** [cerberustesting/cerberus-cicd-gitlab-plugin#1]
Hello, after our upgrade in v4.16 we notice that the ci/cd plugin doesnt work anymore.
The issue is located in line 225 : 
  exit(1) unless res.body.include? 'succesfully inserted to queue'

As the sentence has been updated in cerberus to successfully inserted to queue' (with 2 s on successfully )

**Comment by vertigo17** [comment]
Fixed with https://github.com/cerberustesting/cerberus-cicd-gitlab-plugin/commit/683b62a92d74038f5d1f71682f9d4a55bdf29d81
